### ISSUE TITLE
Prioritized Experience Replay 

### ISSUE THREAD

**Issue by Oktai15** [danaugrs/huskarl#1]
Hi, great work!

Will you plan to add prioritized replay in short time? For example, I found great implementation: https://github.com/alexbooth/DDQN-PER/blob/master/replay_memory.py

**Comment by danaugrs** [comment]
Hi, thanks!

Seems straightforward to implement - I'll try to add it to the project shortly.

**Comment by danaugrs** [comment]
I created this StackOverflow question: https://stackoverflow.com/questions/56507941/how-to-trigger-a-python-function-inside-a-tf-keras-custom-loss-function

**Comment by danaugrs** [comment]
It's implemented! 😄 https://github.com/danaugrs/huskarl/commit/8b5829eb4ee21f0e74cdd2710e797c6c72ec5b2c
